import { writeFileSync, readFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";
import type { RouteManifest } from "./types.ts";

// ─── Route Types Generator ────────────────────────────────
// Generates .bosia/types/src/routes/**/$types.d.ts for each
// route directory. Combined with rootDirs in tsconfig.json,
// this allows `import type { PageData } from './$types'` to
// work in +page.svelte files — identical to SvelteKit's API.

function routeDirOf(filePath: string): string {
	const parts = filePath.replace(/\\/g, "/").split("/");
	parts.pop();
	return parts.join("/") || ".";
}

function paramsForDir(dir: string): string[] {
	if (dir === ".") return [];
	const segs = dir
		.split("/")
		.filter(Boolean)
		.filter((s) => !/^\(.*\)$/.test(s));
	const out: string[] = [];
	for (const seg of segs) {
		const catchAll = seg.match(/^\[\.\.\.(\w+)\]$/);
		if (catchAll) {
			out.push(catchAll[1]!);
			continue;
		}
		const dyn = seg.match(/^\[(\w+)\]$/);
		if (dyn) out.push(dyn[1]!);
	}
	return out;
}

export function generateRouteTypes(manifest: RouteManifest): void {
	// Collect { dir → { pageServer?, layoutServer? } }
	const dirs = new Map<string, { pageServer?: string; layoutServer?: string }>();

	for (const route of manifest.pages) {
		const pageDir = routeDirOf(route.page);
		if (!dirs.has(pageDir)) dirs.set(pageDir, {});
		if (route.pageServer) {
			dirs.get(pageDir)!.pageServer = route.pageServer;
		}
		for (const ls of route.layoutServers) {
			const lsDir = routeDirOf(ls.path);
			if (!dirs.has(lsDir)) dirs.set(lsDir, {});
			dirs.get(lsDir)!.layoutServer = ls.path;
		}
	}

	if (manifest.errorPage && !dirs.has(".")) dirs.set(".", {});

	for (const [dir, info] of dirs) {
		// Path segments of the route dir (empty array for root ".")
		const segments = dir === "." ? [] : dir.split("/").filter(Boolean);

		// Depth of the generated file from project root:
		// .bosia/ + types/ + src/ + routes/ + ...segments
		const depth = 4 + segments.length;
		const up = "../".repeat(depth);
		const srcBase = `${up}src/routes/${segments.length ? segments.join("/") + "/" : ""}`;

		const params = paramsForDir(dir);
		const paramsType =
			params.length === 0 ? `{}` : `{ ${params.map((p) => `${p}: string`).join("; ")} }`;

		const lines: string[] = ["// AUTO-GENERATED by bosia — do not edit\n"];
		lines.push(
			`import type { LoadEvent, MetadataEvent, RequestEvent, Metadata } from 'bosia';`,
		);
		lines.push(``);
		lines.push(`export type Params = ${paramsType};`);
		lines.push(``);
		lines.push(`type _LoadEvent = Omit<LoadEvent, 'params'> & { params: Params };`);
		lines.push(`type _MetadataEvent = Omit<MetadataEvent, 'params'> & { params: Params };`);
		lines.push(`type _RequestEvent = Omit<RequestEvent, 'params'> & { params: Params };`);

		if (info.pageServer) {
			lines.push(``);
			lines.push(`import type { load as _pageLoad } from '${srcBase}+page.server.ts';`);
			lines.push(`export type PageServerLoad = (event: _LoadEvent) => any;`);
			lines.push(
				`export type PageMetadataLoad = (event: _MetadataEvent) => Metadata | Promise<Metadata>;`,
			);
			lines.push(`export type Action = (event: _RequestEvent) => any;`);
			lines.push(
				`export type PageData = Awaited<ReturnType<typeof _pageLoad>> & { params: Params };`,
			);
		} else {
			lines.push(``);
			lines.push(
				`export type PageMetadataLoad = (event: _MetadataEvent) => Metadata | Promise<Metadata>;`,
			);
			lines.push(`export type Action = (event: _RequestEvent) => any;`);
			lines.push(`export type PageData = { params: Params };`);
		}
		lines.push(`export type PageProps = { data: PageData };`);

		if (dir === "." && manifest.errorPage) {
			lines.push(``);
			lines.push(`export type PageError = { status: number; message: string };`);
			lines.push(`export type ErrorProps = { error: PageError };`);
		}

		// ActionData — union of all action return types, unwrapping ActionFailure
		if (info.pageServer) {
			lines.push(``);
			lines.push(`import type { actions as _actions } from '${srcBase}+page.server.ts';`);
			lines.push(
				`type _ActionReturn<T> = T extends (...args: any[]) => infer R ? Awaited<R> : never;`,
			);
			lines.push(
				`type _UnwrapFailure<T> = T extends { status: number; data: infer D } ? D : T;`,
			);
			lines.push(
				`export type ActionData = _actions extends Record<string, (...args: any[]) => any>`,
			);
			lines.push(`  ? _UnwrapFailure<_ActionReturn<_actions[keyof _actions]>> | null`);
			lines.push(`  : null;`);
		}

		if (info.layoutServer) {
			lines.push(`\nimport type { load as _layoutLoad } from '${srcBase}+layout.server.ts';`);
			lines.push(`export type LayoutServerLoad = (event: _LoadEvent) => any;`);
			lines.push(
				`export type LayoutData = Awaited<ReturnType<typeof _layoutLoad>> & { params: Params };`,
			);
			lines.push(`export type LayoutProps = { data: LayoutData; children: any };`);
		}

		const outDir = join(process.cwd(), ".bosia", "types", "src", "routes", ...segments);
		mkdirSync(outDir, { recursive: true });
		writeFileSync(join(outDir, "$types.d.ts"), lines.join("\n") + "\n");
	}

	console.log(
		`✅ Route types generated: .bosia/types/ (${dirs.size} route director${dirs.size === 1 ? "y" : "ies"})`,
	);
}

// ─── Ensure tsconfig rootDirs ─────────────────────────────
// Adds ".bosia/types" to rootDirs so TypeScript resolves
// `./$types` imports via the generated declaration files.
// Only patches the file if rootDirs is not already set.

export function ensureRootDirs(): void {
	const tsconfigPath = join(process.cwd(), "tsconfig.json");
	if (!existsSync(tsconfigPath)) return;

	let tsconfig: any;
	try {
		tsconfig = JSON.parse(readFileSync(tsconfigPath, "utf-8"));
	} catch (err) {
		throw new Error(
			`tsconfig.json at ${tsconfigPath} is invalid JSON: ${(err as Error).message}. Fix the file and re-run.`,
		);
	}

	const rootDirs: string[] = tsconfig.compilerOptions?.rootDirs ?? [];
	if (rootDirs.includes(".bosia/types")) return;

	tsconfig.compilerOptions ??= {};
	tsconfig.compilerOptions.rootDirs = [
		".",
		".bosia/types",
		...rootDirs.filter((d: string) => d !== "."),
	];

	writeFileSync(tsconfigPath, JSON.stringify(tsconfig, null, 2) + "\n");
	console.log("✅ tsconfig.json: added .bosia/types to rootDirs");
}
