import { writeFileSync, readFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";
import type { RouteManifest } from "./types.ts";

// ─── Route Types Generator ────────────────────────────────
// Generates .bunia/types/src/routes/**/$types.d.ts for each
// route directory. Combined with rootDirs in tsconfig.json,
// this allows `import type { PageData } from './$types'` to
// work in +page.svelte files — identical to SvelteKit's API.

function routeDirOf(filePath: string): string {
    const parts = filePath.replace(/\\/g, "/").split("/");
    parts.pop();
    return parts.join("/") || ".";
}

export function generateRouteTypes(manifest: RouteManifest): void {
    // Collect { dir → { pageServer?, layoutServer? } }
    const dirs = new Map<string, { pageServer?: string; layoutServer?: string }>();

    for (const route of manifest.pages) {
        const pageDir = routeDirOf(route.page);
        if (!dirs.has(pageDir)) dirs.set(pageDir, {});
        if (route.pageServer) {
            dirs.get(pageDir)!.pageServer = route.pageServer;
        }
        for (const ls of route.layoutServers) {
            const lsDir = routeDirOf(ls.path);
            if (!dirs.has(lsDir)) dirs.set(lsDir, {});
            dirs.get(lsDir)!.layoutServer = ls.path;
        }
    }

    for (const [dir, info] of dirs) {
        // Path segments of the route dir (empty array for root ".")
        const segments = dir === "." ? [] : dir.split("/").filter(Boolean);

        // Depth of the generated file from project root:
        // .bunia/ + types/ + src/ + routes/ + ...segments
        const depth = 4 + segments.length;
        const up = "../".repeat(depth);
        const srcBase = `${up}src/routes/${segments.length ? segments.join("/") + "/" : ""}`;

        const lines: string[] = ["// AUTO-GENERATED by bunia — do not edit\n"];

        if (info.pageServer) {
            lines.push(`import type { load as _pageLoad } from '${srcBase}+page.server.ts';`);
            lines.push(`export type PageData = Awaited<ReturnType<typeof _pageLoad>> & { params: Record<string, string> };`);
        } else {
            lines.push(`export type PageData = { params: Record<string, string> };`);
        }
        lines.push(`export type PageProps = { data: PageData };`);

        // ActionData — union of all action return types, unwrapping ActionFailure
        if (info.pageServer) {
            lines.push(``);
            lines.push(`import type { actions as _actions } from '${srcBase}+page.server.ts';`);
            lines.push(`type _ActionReturn<T> = T extends (...args: any[]) => infer R ? Awaited<R> : never;`);
            lines.push(`type _UnwrapFailure<T> = T extends { status: number; data: infer D } ? D : T;`);
            lines.push(`export type ActionData = _actions extends Record<string, (...args: any[]) => any>`);
            lines.push(`  ? _UnwrapFailure<_ActionReturn<_actions[keyof _actions]>> | null`);
            lines.push(`  : null;`);
        }

        if (info.layoutServer) {
            lines.push(`\nimport type { load as _layoutLoad } from '${srcBase}+layout.server.ts';`);
            lines.push(`export type LayoutData = Awaited<ReturnType<typeof _layoutLoad>> & { params: Record<string, string> };`);
            lines.push(`export type LayoutProps = { data: LayoutData; children: any };`);
        }

        const outDir = join(process.cwd(), ".bunia", "types", "src", "routes", ...segments);
        mkdirSync(outDir, { recursive: true });
        writeFileSync(join(outDir, "$types.d.ts"), lines.join("\n") + "\n");
    }

    console.log(`✅ Route types generated: .bunia/types/ (${dirs.size} route director${dirs.size === 1 ? "y" : "ies"})`);
}

// ─── Ensure tsconfig rootDirs ─────────────────────────────
// Adds ".bunia/types" to rootDirs so TypeScript resolves
// `./$types` imports via the generated declaration files.
// Only patches the file if rootDirs is not already set.

export function ensureRootDirs(): void {
    const tsconfigPath = join(process.cwd(), "tsconfig.json");
    if (!existsSync(tsconfigPath)) return;

    let tsconfig: any;
    try {
        tsconfig = JSON.parse(readFileSync(tsconfigPath, "utf-8"));
    } catch {
        console.warn("⚠️  Could not parse tsconfig.json — add rootDirs manually:\n" +
            '   "rootDirs": [".", ".bunia/types"]');
        return;
    }

    const rootDirs: string[] = tsconfig.compilerOptions?.rootDirs ?? [];
    if (rootDirs.includes(".bunia/types")) return;

    tsconfig.compilerOptions ??= {};
    tsconfig.compilerOptions.rootDirs = [".", ".bunia/types",
        ...rootDirs.filter((d: string) => d !== ".")];

    writeFileSync(tsconfigPath, JSON.stringify(tsconfig, null, 2) + "\n");
    console.log("✅ tsconfig.json: added .bunia/types to rootDirs");
}
